# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get secrets from Vault
        id: vault
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: ${{ secrets.VAULT_URL }}
          method: approle
          roleId: ${{ secrets.GTA_VAULT_ROLEID }}
          secretId: ${{ secrets.GTA_VAULT_SECRETID }}
          secrets: |
            jenkins/jfrog/service-accounts/coretech username ;
            jenkins/jfrog/service-accounts/coretech password

      - name: Set gradlew property
        run: |
          echo "ORG_GRADLE_PROJECT_artifactory_context_url=${{ secrets.ARTIFACTORY_URL }}" >> $GITHUB_ENV
          echo "ORG_GRADLE_PROJECT_artifactory_libs_repo_key=libs-release" >> $GITHUB_ENV
          echo "ORG_GRADLE_PROJECT_artifactory_plugins_repo_key=plugins-release" >> $GITHUB_ENV
          echo "ORG_GRADLE_PROJECT_artifactory_user=${{ steps.vault.outputs.username }}" >> $GITHUB_ENV
          echo "ORG_GRADLE_PROJECT_artifactory_password=${{ steps.vault.outputs.password }}" >> $GITHUB_ENV

      - name: Run checkstyle and tests with Gradle
        run: ./gradlew clean check -Partifactory
